
2013-10-21 15:17:52
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 15:18:03
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 15:18:11
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 15:18:21
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 15:18:30
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 15:18:33
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 15:18:36
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 15:18:49
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 15:18:51
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 15:18:52
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 15:18:52
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 15:18:54
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 15:18:55
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 15:18:57
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 15:18:58
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 19:15:33
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/proc.py", line 97, in run
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 19:15:41
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/proc.py", line 97, in run
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 19:16:08
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 19:16:13
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 19:16:16
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 19:16:20
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-10-21 19:16:24
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
